[theme]
primaryColor = "#5865F2"
backgroundColor = "#E0E3FF"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#000000"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 200

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"
